/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import Ops.Operations;

/**
 *
 * @author Kris
 */
public class Propuesta extends javax.swing.JFrame {

    int num1, num2, option;
    /**
     * Creates new form Propuesta
     */
    public Propuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ContainerResult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_result = new javax.swing.JTextPane();
        Container_btnPercent = new javax.swing.JPanel();
        lbl_btnPercent = new javax.swing.JLabel();
        Container_btnCE = new javax.swing.JPanel();
        lbl_btnCE = new javax.swing.JLabel();
        Container_btnC = new javax.swing.JPanel();
        lbl_btnC = new javax.swing.JLabel();
        Container_btnDelete = new javax.swing.JPanel();
        lbl_btnDelete = new javax.swing.JLabel();
        Container_btnInvertOf = new javax.swing.JPanel();
        lbl_btnInvertOf = new javax.swing.JLabel();
        Container_btnX2 = new javax.swing.JPanel();
        lbl_btnX2 = new javax.swing.JLabel();
        Container_btnSqrRoot = new javax.swing.JPanel();
        lbl_btnSqrRoot = new javax.swing.JLabel();
        Container_btnDiv = new javax.swing.JPanel();
        lbl_btnDiv = new javax.swing.JLabel();
        Container_btn7 = new javax.swing.JPanel();
        lbl_btn7 = new javax.swing.JLabel();
        Container_btn8 = new javax.swing.JPanel();
        lbl_btn8 = new javax.swing.JLabel();
        Container_btn9 = new javax.swing.JPanel();
        lbl_btn9 = new javax.swing.JLabel();
        Container_btnMultiply = new javax.swing.JPanel();
        lbl_btnMultiply = new javax.swing.JLabel();
        Container_btn4 = new javax.swing.JPanel();
        lbl_btn4 = new javax.swing.JLabel();
        Container_btn5 = new javax.swing.JPanel();
        lbl_btn5 = new javax.swing.JLabel();
        Container_btn6 = new javax.swing.JPanel();
        lbl_btn6 = new javax.swing.JLabel();
        Container_btnSubstract = new javax.swing.JPanel();
        lbl_btnSubstract = new javax.swing.JLabel();
        Container_btn1 = new javax.swing.JPanel();
        lbl_btn1 = new javax.swing.JLabel();
        Container_btn2 = new javax.swing.JPanel();
        lbl_btn2 = new javax.swing.JLabel();
        Container_btn3 = new javax.swing.JPanel();
        lbl_btn3 = new javax.swing.JLabel();
        Container_btnAddition = new javax.swing.JPanel();
        lbl_btnAddition = new javax.swing.JLabel();
        Container_btnInvert = new javax.swing.JPanel();
        lbl_btnInvert = new javax.swing.JLabel();
        Container_btn0 = new javax.swing.JPanel();
        lbl_btn0 = new javax.swing.JLabel();
        Container_btnDecimal = new javax.swing.JPanel();
        lbl_btnDecimal = new javax.swing.JLabel();
        Container_btnEqual = new javax.swing.JPanel();
        lbl_btnEqual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(310, 500));

        txt_result.setEditable(false);
        txt_result.setBackground(new java.awt.Color(255, 255, 255));
        txt_result.setBorder(null);
        txt_result.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        txt_result.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_result.setEnabled(false);
        txt_result.setFocusable(false);
        txt_result.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txt_result);

        javax.swing.GroupLayout ContainerResultLayout = new javax.swing.GroupLayout(ContainerResult);
        ContainerResult.setLayout(ContainerResultLayout);
        ContainerResultLayout.setHorizontalGroup(
            ContainerResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerResultLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        ContainerResultLayout.setVerticalGroup(
            ContainerResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Container_btnPercent.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnPercent.setForeground(java.awt.Color.black);
        Container_btnPercent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnPercent.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnPercent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnPercentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnPercentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnPercentMouseExited(evt);
            }
        });

        lbl_btnPercent.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnPercent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnPercent.setText("%");

        javax.swing.GroupLayout Container_btnPercentLayout = new javax.swing.GroupLayout(Container_btnPercent);
        Container_btnPercent.setLayout(Container_btnPercentLayout);
        Container_btnPercentLayout.setHorizontalGroup(
            Container_btnPercentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnPercent, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnPercentLayout.setVerticalGroup(
            Container_btnPercentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnPercent, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnCE.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnCE.setForeground(java.awt.Color.black);
        Container_btnCE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnCE.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnCEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnCEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnCEMouseExited(evt);
            }
        });

        lbl_btnCE.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnCE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnCE.setText("CE");

        javax.swing.GroupLayout Container_btnCELayout = new javax.swing.GroupLayout(Container_btnCE);
        Container_btnCE.setLayout(Container_btnCELayout);
        Container_btnCELayout.setHorizontalGroup(
            Container_btnCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnCE, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnCELayout.setVerticalGroup(
            Container_btnCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnCE, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnC.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnC.setForeground(java.awt.Color.black);
        Container_btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnC.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnCMouseExited(evt);
            }
        });

        lbl_btnC.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnC.setText("C");

        javax.swing.GroupLayout Container_btnCLayout = new javax.swing.GroupLayout(Container_btnC);
        Container_btnC.setLayout(Container_btnCLayout);
        Container_btnCLayout.setHorizontalGroup(
            Container_btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnC, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnCLayout.setVerticalGroup(
            Container_btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnC, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnDelete.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnDelete.setForeground(java.awt.Color.black);
        Container_btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnDelete.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnDeleteMouseExited(evt);
            }
        });

        lbl_btnDelete.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnDelete.setText("←");

        javax.swing.GroupLayout Container_btnDeleteLayout = new javax.swing.GroupLayout(Container_btnDelete);
        Container_btnDelete.setLayout(Container_btnDeleteLayout);
        Container_btnDeleteLayout.setHorizontalGroup(
            Container_btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnDeleteLayout.setVerticalGroup(
            Container_btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnInvertOf.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnInvertOf.setForeground(java.awt.Color.black);
        Container_btnInvertOf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnInvertOf.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnInvertOf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnInvertOfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnInvertOfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnInvertOfMouseExited(evt);
            }
        });

        lbl_btnInvertOf.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnInvertOf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnInvertOf.setText("1/x");

        javax.swing.GroupLayout Container_btnInvertOfLayout = new javax.swing.GroupLayout(Container_btnInvertOf);
        Container_btnInvertOf.setLayout(Container_btnInvertOfLayout);
        Container_btnInvertOfLayout.setHorizontalGroup(
            Container_btnInvertOfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnInvertOf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Container_btnInvertOfLayout.setVerticalGroup(
            Container_btnInvertOfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnInvertOf, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnX2.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnX2.setForeground(java.awt.Color.black);
        Container_btnX2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnX2.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnX2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnX2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnX2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnX2MouseExited(evt);
            }
        });

        lbl_btnX2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnX2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnX2.setText("x2");

        javax.swing.GroupLayout Container_btnX2Layout = new javax.swing.GroupLayout(Container_btnX2);
        Container_btnX2.setLayout(Container_btnX2Layout);
        Container_btnX2Layout.setHorizontalGroup(
            Container_btnX2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnX2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnX2Layout.setVerticalGroup(
            Container_btnX2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnX2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnSqrRoot.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnSqrRoot.setForeground(java.awt.Color.black);
        Container_btnSqrRoot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnSqrRoot.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnSqrRoot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnSqrRootMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnSqrRootMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnSqrRootMouseExited(evt);
            }
        });

        lbl_btnSqrRoot.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnSqrRoot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnSqrRoot.setText("√X");

        javax.swing.GroupLayout Container_btnSqrRootLayout = new javax.swing.GroupLayout(Container_btnSqrRoot);
        Container_btnSqrRoot.setLayout(Container_btnSqrRootLayout);
        Container_btnSqrRootLayout.setHorizontalGroup(
            Container_btnSqrRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container_btnSqrRootLayout.createSequentialGroup()
                .addComponent(lbl_btnSqrRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Container_btnSqrRootLayout.setVerticalGroup(
            Container_btnSqrRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnSqrRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnDiv.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnDiv.setForeground(java.awt.Color.black);
        Container_btnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnDiv.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnDivMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnDivMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnDivMouseExited(evt);
            }
        });

        lbl_btnDiv.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnDiv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnDiv.setText("÷");

        javax.swing.GroupLayout Container_btnDivLayout = new javax.swing.GroupLayout(Container_btnDiv);
        Container_btnDiv.setLayout(Container_btnDivLayout);
        Container_btnDivLayout.setHorizontalGroup(
            Container_btnDivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnDivLayout.setVerticalGroup(
            Container_btnDivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn7.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn7.setForeground(java.awt.Color.black);
        Container_btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn7.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn7MouseExited(evt);
            }
        });

        lbl_btn7.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn7.setText("7");

        javax.swing.GroupLayout Container_btn7Layout = new javax.swing.GroupLayout(Container_btn7);
        Container_btn7.setLayout(Container_btn7Layout);
        Container_btn7Layout.setHorizontalGroup(
            Container_btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn7Layout.setVerticalGroup(
            Container_btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn8.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn8.setForeground(java.awt.Color.black);
        Container_btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn8.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn8MouseExited(evt);
            }
        });

        lbl_btn8.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn8.setText("8");

        javax.swing.GroupLayout Container_btn8Layout = new javax.swing.GroupLayout(Container_btn8);
        Container_btn8.setLayout(Container_btn8Layout);
        Container_btn8Layout.setHorizontalGroup(
            Container_btn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn8Layout.setVerticalGroup(
            Container_btn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn9.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn9.setForeground(java.awt.Color.black);
        Container_btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn9.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn9MouseExited(evt);
            }
        });

        lbl_btn9.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn9.setText("9");

        javax.swing.GroupLayout Container_btn9Layout = new javax.swing.GroupLayout(Container_btn9);
        Container_btn9.setLayout(Container_btn9Layout);
        Container_btn9Layout.setHorizontalGroup(
            Container_btn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn9Layout.setVerticalGroup(
            Container_btn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnMultiply.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnMultiply.setForeground(java.awt.Color.black);
        Container_btnMultiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnMultiply.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnMultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnMultiplyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnMultiplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnMultiplyMouseExited(evt);
            }
        });

        lbl_btnMultiply.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnMultiply.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnMultiply.setText("×");

        javax.swing.GroupLayout Container_btnMultiplyLayout = new javax.swing.GroupLayout(Container_btnMultiply);
        Container_btnMultiply.setLayout(Container_btnMultiplyLayout);
        Container_btnMultiplyLayout.setHorizontalGroup(
            Container_btnMultiplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnMultiplyLayout.setVerticalGroup(
            Container_btnMultiplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn4.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn4.setForeground(java.awt.Color.black);
        Container_btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn4.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn4MouseExited(evt);
            }
        });

        lbl_btn4.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn4.setText("4");

        javax.swing.GroupLayout Container_btn4Layout = new javax.swing.GroupLayout(Container_btn4);
        Container_btn4.setLayout(Container_btn4Layout);
        Container_btn4Layout.setHorizontalGroup(
            Container_btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn4Layout.setVerticalGroup(
            Container_btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn5.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn5.setForeground(java.awt.Color.black);
        Container_btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn5.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn5MouseExited(evt);
            }
        });

        lbl_btn5.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn5.setText("5");

        javax.swing.GroupLayout Container_btn5Layout = new javax.swing.GroupLayout(Container_btn5);
        Container_btn5.setLayout(Container_btn5Layout);
        Container_btn5Layout.setHorizontalGroup(
            Container_btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn5Layout.setVerticalGroup(
            Container_btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn6.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn6.setForeground(java.awt.Color.black);
        Container_btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn6.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn6MouseExited(evt);
            }
        });

        lbl_btn6.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn6.setText("6");

        javax.swing.GroupLayout Container_btn6Layout = new javax.swing.GroupLayout(Container_btn6);
        Container_btn6.setLayout(Container_btn6Layout);
        Container_btn6Layout.setHorizontalGroup(
            Container_btn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn6Layout.setVerticalGroup(
            Container_btn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnSubstract.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnSubstract.setForeground(java.awt.Color.black);
        Container_btnSubstract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnSubstract.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnSubstract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnSubstractMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnSubstractMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnSubstractMouseExited(evt);
            }
        });

        lbl_btnSubstract.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnSubstract.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnSubstract.setText("-");

        javax.swing.GroupLayout Container_btnSubstractLayout = new javax.swing.GroupLayout(Container_btnSubstract);
        Container_btnSubstract.setLayout(Container_btnSubstractLayout);
        Container_btnSubstractLayout.setHorizontalGroup(
            Container_btnSubstractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnSubstract, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnSubstractLayout.setVerticalGroup(
            Container_btnSubstractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnSubstract, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn1.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn1.setForeground(java.awt.Color.black);
        Container_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn1.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn1MouseExited(evt);
            }
        });

        lbl_btn1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn1.setText("1");

        javax.swing.GroupLayout Container_btn1Layout = new javax.swing.GroupLayout(Container_btn1);
        Container_btn1.setLayout(Container_btn1Layout);
        Container_btn1Layout.setHorizontalGroup(
            Container_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn1Layout.setVerticalGroup(
            Container_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn2.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn2.setForeground(java.awt.Color.black);
        Container_btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn2.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn2MouseExited(evt);
            }
        });

        lbl_btn2.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn2.setText("2");

        javax.swing.GroupLayout Container_btn2Layout = new javax.swing.GroupLayout(Container_btn2);
        Container_btn2.setLayout(Container_btn2Layout);
        Container_btn2Layout.setHorizontalGroup(
            Container_btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn2Layout.setVerticalGroup(
            Container_btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn3.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn3.setForeground(java.awt.Color.black);
        Container_btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn3.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn3MouseExited(evt);
            }
        });

        lbl_btn3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn3.setText("3");

        javax.swing.GroupLayout Container_btn3Layout = new javax.swing.GroupLayout(Container_btn3);
        Container_btn3.setLayout(Container_btn3Layout);
        Container_btn3Layout.setHorizontalGroup(
            Container_btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn3Layout.setVerticalGroup(
            Container_btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnAddition.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnAddition.setForeground(java.awt.Color.black);
        Container_btnAddition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnAddition.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnAddition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnAdditionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnAdditionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnAdditionMouseExited(evt);
            }
        });

        lbl_btnAddition.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnAddition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnAddition.setText("+");

        javax.swing.GroupLayout Container_btnAdditionLayout = new javax.swing.GroupLayout(Container_btnAddition);
        Container_btnAddition.setLayout(Container_btnAdditionLayout);
        Container_btnAdditionLayout.setHorizontalGroup(
            Container_btnAdditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnAddition, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnAdditionLayout.setVerticalGroup(
            Container_btnAdditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnAddition, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnInvert.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnInvert.setForeground(java.awt.Color.black);
        Container_btnInvert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnInvert.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnInvert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnInvertMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnInvertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnInvertMouseExited(evt);
            }
        });

        lbl_btnInvert.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnInvert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnInvert.setText("+/-");

        javax.swing.GroupLayout Container_btnInvertLayout = new javax.swing.GroupLayout(Container_btnInvert);
        Container_btnInvert.setLayout(Container_btnInvertLayout);
        Container_btnInvertLayout.setHorizontalGroup(
            Container_btnInvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnInvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Container_btnInvertLayout.setVerticalGroup(
            Container_btnInvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnInvert, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btn0.setBackground(new java.awt.Color(204, 51, 0));
        Container_btn0.setForeground(java.awt.Color.black);
        Container_btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btn0.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btn0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btn0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btn0MouseExited(evt);
            }
        });

        lbl_btn0.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btn0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn0.setText("0");

        javax.swing.GroupLayout Container_btn0Layout = new javax.swing.GroupLayout(Container_btn0);
        Container_btn0.setLayout(Container_btn0Layout);
        Container_btn0Layout.setHorizontalGroup(
            Container_btn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btn0Layout.setVerticalGroup(
            Container_btn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnDecimal.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnDecimal.setForeground(java.awt.Color.black);
        Container_btnDecimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnDecimal.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnDecimalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnDecimalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnDecimalMouseExited(evt);
            }
        });

        lbl_btnDecimal.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnDecimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnDecimal.setText(",");

        javax.swing.GroupLayout Container_btnDecimalLayout = new javax.swing.GroupLayout(Container_btnDecimal);
        Container_btnDecimal.setLayout(Container_btnDecimalLayout);
        Container_btnDecimalLayout.setHorizontalGroup(
            Container_btnDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnDecimalLayout.setVerticalGroup(
            Container_btnDecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Container_btnEqual.setBackground(new java.awt.Color(204, 51, 0));
        Container_btnEqual.setForeground(java.awt.Color.black);
        Container_btnEqual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Container_btnEqual.setPreferredSize(new java.awt.Dimension(60, 50));
        Container_btnEqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Container_btnEqualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Container_btnEqualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Container_btnEqualMouseExited(evt);
            }
        });

        lbl_btnEqual.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lbl_btnEqual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btnEqual.setText("=");

        javax.swing.GroupLayout Container_btnEqualLayout = new javax.swing.GroupLayout(Container_btnEqual);
        Container_btnEqual.setLayout(Container_btnEqualLayout);
        Container_btnEqualLayout.setHorizontalGroup(
            Container_btnEqualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        Container_btnEqualLayout.setVerticalGroup(
            Container_btnEqualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContainerResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Container_btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnInvertOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnInvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Container_btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Container_btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnSqrRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Container_btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Container_btnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ContainerResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Container_btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnInvertOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnInvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Container_btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Container_btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnSqrRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Container_btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Container_btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Container_btnPercentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnPercentMouseExited
        Container_btnPercent.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnPercentMouseExited

    private void Container_btnPercentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnPercentMouseEntered
        Container_btnPercent.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnPercentMouseEntered

    private void Container_btnPercentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnPercentMouseClicked
        txt_result.setText(lbl_btnPercent.getText());
    }//GEN-LAST:event_Container_btnPercentMouseClicked

    private void Container_btnInvertOfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnInvertOfMouseClicked
        // TODO
    }//GEN-LAST:event_Container_btnInvertOfMouseClicked

    private void Container_btnInvertOfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnInvertOfMouseEntered
       Container_btnInvertOf.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnInvertOfMouseEntered

    private void Container_btnInvertOfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnInvertOfMouseExited
        Container_btnInvertOf.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnInvertOfMouseExited

    private void Container_btn7MouseClicked(java.awt.event.MouseEvent evt) {                                            
        txt_result.setText(txt_result.getText()+lbl_btn7.getText());
    }                                            

    private void Container_btn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn7MouseEntered
        Container_btn7.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn7MouseEntered

    private void Container_btn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn7MouseExited
        Container_btn7.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn7MouseExited

    private void Container_btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn4MouseClicked
        txt_result.setText(txt_result.getText()+lbl_btn4.getText());
    }//GEN-LAST:event_Container_btn4MouseClicked

    private void Container_btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn4MouseEntered
        Container_btn4.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn4MouseEntered

    private void Container_btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn4MouseExited
        Container_btn4.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn4MouseExited

    private void Container_btnCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnCEMouseClicked
        txt_result.setText("");
    }//GEN-LAST:event_Container_btnCEMouseClicked

    private void Container_btnCEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnCEMouseEntered
        Container_btnCE.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnCEMouseEntered

    private void Container_btnCEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnCEMouseExited
        Container_btnCE.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnCEMouseExited

    private void Container_btnX2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnX2MouseClicked
        // todo
    }//GEN-LAST:event_Container_btnX2MouseClicked

    private void Container_btnX2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnX2MouseEntered
        Container_btnX2.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnX2MouseEntered

    private void Container_btnX2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnX2MouseExited
        Container_btnX2.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnX2MouseExited

    private void Container_btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn8MouseClicked
        txt_result.setText(txt_result.getText()+lbl_btn8.getText());
    }//GEN-LAST:event_Container_btn8MouseClicked

    private void Container_btn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn8MouseEntered
        Container_btn8.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn8MouseEntered

    private void Container_btn8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn8MouseExited
        Container_btn8.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn8MouseExited

    private void Container_btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn5MouseClicked
        txt_result.setText(txt_result.getText()+lbl_btn5.getText());
    }//GEN-LAST:event_Container_btn5MouseClicked

    private void Container_btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn5MouseEntered
        Container_btn5.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn5MouseEntered

    private void Container_btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn5MouseExited
        Container_btn5.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn5MouseExited

    private void Container_btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn0MouseClicked
        txt_result.setText(lbl_btn0.getText());
    }//GEN-LAST:event_Container_btn0MouseClicked

    private void Container_btn0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn0MouseEntered
        Container_btn0.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn0MouseEntered

    private void Container_btn0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn0MouseExited
        Container_btn0.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn0MouseExited

    private void Container_btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn2MouseClicked
        txt_result.setText(txt_result.getText()+lbl_btn2.getText());
    }//GEN-LAST:event_Container_btn2MouseClicked

    private void Container_btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn2MouseEntered
        Container_btn2.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn2MouseEntered

    private void Container_btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn2MouseExited
        Container_btn2.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn2MouseExited

    private void Container_btnInvertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnInvertMouseClicked
        int actualLabel = Integer.parseInt(txt_result.getText());

        if(actualLabel > 0){
            txt_result.setText(Integer.toString(actualLabel*-1));
        }
        else if (actualLabel < 0){
            txt_result.setText(Integer.toString(actualLabel*-1));
        }
    }//GEN-LAST:event_Container_btnInvertMouseClicked

    private void Container_btnInvertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnInvertMouseEntered
        Container_btnInvert.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnInvertMouseEntered

    private void Container_btnInvertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnInvertMouseExited
        Container_btnInvert.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnInvertMouseExited

    private void Container_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn1MouseClicked
        txt_result.setText(txt_result.getText()+lbl_btn1.getText());
    }//GEN-LAST:event_Container_btn1MouseClicked

    private void Container_btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn1MouseEntered
        Container_btn1.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn1MouseEntered

    private void Container_btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn1MouseExited
        Container_btn1.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn1MouseExited

    private void Container_btnCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnCMouseClicked
        txt_result.setText("");
    }//GEN-LAST:event_Container_btnCMouseClicked

    private void Container_btnCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnCMouseEntered
        Container_btnC.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnCMouseEntered

    private void Container_btnCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnCMouseExited
        Container_btnC.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnCMouseExited

    private void Container_btnSqrRootMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnSqrRootMouseClicked
        // TODO
    }//GEN-LAST:event_Container_btnSqrRootMouseClicked

    private void Container_btnSqrRootMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnSqrRootMouseEntered
        Container_btnSqrRoot.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnSqrRootMouseEntered

    private void Container_btnSqrRootMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnSqrRootMouseExited
        Container_btnSqrRoot.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnSqrRootMouseExited

    private void Container_btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn9MouseClicked
        txt_result.setText(txt_result.getText()+lbl_btn9.getText());
    }//GEN-LAST:event_Container_btn9MouseClicked

    private void Container_btn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn9MouseEntered
        Container_btn9.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn9MouseEntered

    private void Container_btn9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn9MouseExited
        Container_btn9.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn9MouseExited

    private void Container_btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn6MouseClicked
        txt_result.setText(txt_result.getText()+lbl_btn6.getText());
    }//GEN-LAST:event_Container_btn6MouseClicked

    private void Container_btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn6MouseEntered
        Container_btn6.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn6MouseEntered

    private void Container_btn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn6MouseExited
        Container_btn6.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn6MouseExited

    private void Container_btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDeleteMouseClicked
        txt_result.setText(txt_result.getText().substring(0, txt_result.getText().length()-1));
    }//GEN-LAST:event_Container_btnDeleteMouseClicked

    private void Container_btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDeleteMouseEntered
        Container_btnDelete.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnDeleteMouseEntered

    private void Container_btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDeleteMouseExited
        Container_btnDelete.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnDeleteMouseExited

    private void Container_btnDivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDivMouseClicked
        num1 = Integer.parseInt(txt_result.getText());
        txt_result.setText("");
        option = 4;
    }//GEN-LAST:event_Container_btnDivMouseClicked

    private void Container_btnDivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDivMouseEntered
        Container_btnDiv.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnDivMouseEntered

    private void Container_btnDivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDivMouseExited
        Container_btnDiv.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnDivMouseExited

    private void Container_btnMultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnMultiplyMouseClicked
        num1 = Integer.parseInt(txt_result.getText());
        txt_result.setText("");
        option = 3;
    }//GEN-LAST:event_Container_btnMultiplyMouseClicked

    private void Container_btnMultiplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnMultiplyMouseEntered
        Container_btnMultiply.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnMultiplyMouseEntered

    private void Container_btnMultiplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnMultiplyMouseExited
        Container_btnMultiply.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnMultiplyMouseExited

    private void Container_btnSubstractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnSubstractMouseClicked
        num1 = Integer.parseInt(txt_result.getText());
        txt_result.setText("");
        option = 2;
    }//GEN-LAST:event_Container_btnSubstractMouseClicked

    private void Container_btnSubstractMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnSubstractMouseEntered
        Container_btnSubstract.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnSubstractMouseEntered

    private void Container_btnSubstractMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnSubstractMouseExited
        Container_btnSubstract.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnSubstractMouseExited

    private void Container_btnEqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnEqualMouseClicked
        num2 = Integer.parseInt(txt_result.getText());
        switch (option) {
            case 1: // Addition
                txt_result.setText(Integer.toString(Operations.Addition(num1, num2)));
                break;

            case 2: // Substract
                txt_result.setText(Integer.toString(Operations.Substract(num1, num2)));
                break;

            case 3: // Multiply
                txt_result.setText(Integer.toString(Operations.Multiply(num1, num2)));
                break;

            case 4: // Div
                txt_result.setText((Double.toString(Operations.Divide(num1, num2))));
                break;
            default: //do nothing XD
                break;
        }



    }//GEN-LAST:event_Container_btnEqualMouseClicked

    private void Container_btnEqualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnEqualMouseEntered
        Container_btnEqual.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnEqualMouseEntered

    private void Container_btnEqualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnEqualMouseExited
        Container_btnEqual.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnEqualMouseExited

    private void Container_btnAdditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnAdditionMouseClicked
        num1 = Integer.parseInt(txt_result.getText());
        txt_result.setText("");
        option = 1;
    }//GEN-LAST:event_Container_btnAdditionMouseClicked

    private void Container_btnAdditionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnAdditionMouseEntered
        Container_btnAddition.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnAdditionMouseEntered

    private void Container_btnAdditionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnAdditionMouseExited
        Container_btnAddition.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnAdditionMouseExited

    private void Container_btnDecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDecimalMouseClicked
        // TODO
    }//GEN-LAST:event_Container_btnDecimalMouseClicked

    private void Container_btnDecimalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDecimalMouseEntered
        Container_btnDecimal.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btnDecimalMouseEntered

    private void Container_btnDecimalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btnDecimalMouseExited
        Container_btnDecimal.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btnDecimalMouseExited

    private void Container_btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn3MouseClicked
        txt_result.setText(txt_result.getText()+lbl_btn3.getText());
    }//GEN-LAST:event_Container_btn3MouseClicked

    private void Container_btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn3MouseEntered
        Container_btn3.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_Container_btn3MouseEntered

    private void Container_btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Container_btn3MouseExited
        Container_btn3.setBackground(Color.GRAY);
    }//GEN-LAST:event_Container_btn3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Propuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Propuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Propuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Propuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Propuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContainerResult;
    private javax.swing.JPanel Container_btn0;
    private javax.swing.JPanel Container_btn1;
    private javax.swing.JPanel Container_btn2;
    private javax.swing.JPanel Container_btn3;
    private javax.swing.JPanel Container_btn4;
    private javax.swing.JPanel Container_btn5;
    private javax.swing.JPanel Container_btn6;
    private javax.swing.JPanel Container_btn7;
    private javax.swing.JPanel Container_btn8;
    private javax.swing.JPanel Container_btn9;
    private javax.swing.JPanel Container_btnAddition;
    private javax.swing.JPanel Container_btnC;
    private javax.swing.JPanel Container_btnCE;
    private javax.swing.JPanel Container_btnDecimal;
    private javax.swing.JPanel Container_btnDelete;
    private javax.swing.JPanel Container_btnDiv;
    private javax.swing.JPanel Container_btnEqual;
    private javax.swing.JPanel Container_btnInvert;
    private javax.swing.JPanel Container_btnInvertOf;
    private javax.swing.JPanel Container_btnMultiply;
    private javax.swing.JPanel Container_btnPercent;
    private javax.swing.JPanel Container_btnSqrRoot;
    private javax.swing.JPanel Container_btnSubstract;
    private javax.swing.JPanel Container_btnX2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_btn0;
    private javax.swing.JLabel lbl_btn1;
    private javax.swing.JLabel lbl_btn2;
    private javax.swing.JLabel lbl_btn3;
    private javax.swing.JLabel lbl_btn4;
    private javax.swing.JLabel lbl_btn5;
    private javax.swing.JLabel lbl_btn6;
    private javax.swing.JLabel lbl_btn7;
    private javax.swing.JLabel lbl_btn8;
    private javax.swing.JLabel lbl_btn9;
    private javax.swing.JLabel lbl_btnAddition;
    private javax.swing.JLabel lbl_btnC;
    private javax.swing.JLabel lbl_btnCE;
    private javax.swing.JLabel lbl_btnDecimal;
    private javax.swing.JLabel lbl_btnDelete;
    private javax.swing.JLabel lbl_btnDiv;
    private javax.swing.JLabel lbl_btnEqual;
    private javax.swing.JLabel lbl_btnInvert;
    private javax.swing.JLabel lbl_btnInvertOf;
    private javax.swing.JLabel lbl_btnMultiply;
    private javax.swing.JLabel lbl_btnPercent;
    private javax.swing.JLabel lbl_btnSqrRoot;
    private javax.swing.JLabel lbl_btnSubstract;
    private javax.swing.JLabel lbl_btnX2;
    private javax.swing.JTextPane txt_result;
    // End of variables declaration//GEN-END:variables
}
